apiVersion: v1
kind: Service
metadata:
  name: redis-proxy
spec:
  type: NodePort
  ports:
  - name: redis-proxy
    nodePort: 30001
    port: 7777
    protocol: TCP
    targetPort: 7777
  selector:
    app: redis-proxy
