apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-proxy
data:
  proxy.conf: |
    cluster 10.110.105.37:6379 #resis-cluster svc的ip
    bind 0.0.0.0
    port 7777
    threads 8
    daemonize no
    enable-cross-slot yes
    #auth p3NZuzwDQr
    log-level error
