apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cluster
data:
  update-node.sh: |
    #!/bin/sh
    REDIS_NODES="/data/nodes.conf"
    sed -i -e "/myself/ s/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/${POD_IP}/" ${REDIS_NODES}
    exec "$@"
  users.acl: |
    user default on nopass ~* &* +@all
    user arc on nopass ~* &* +@all
    user larry on nopass ~* &* +@all
  myfile.txt: |
    hello world
  redis.conf: |+
    cluster-enabled yes
    cluster-require-full-coverage yes
    cluster-node-timeout 15000
    cluster-config-file /data/nodes.conf
    cluster-migration-barrier 1
    appendonly yes
    appendfsync always
    protected-mode no
    no-appendfsync-on-rewrite no
    auto-aof-rewrite-min-size 200mb
    auto-aof-rewrite-percentage 200
    aclfile /conf/users.acl
    maxclients 10000
    maxmemory-policy allkeys-lru
    maxmemory 200mb
    maxmemory-samples 5
    maxmemory-eviction-tenacity 10
    replica-ignore-maxmemory yes
